In [1]:
import numpy as np
lst=[10,20,30,40,50,60]
print("Original List:", lst)
lst1=np.array(lst)
print("Numpy Array:", lst1)
print("Data Type of Numpy Array:", lst1.dtype)
print("Shape of Numpy Array:", lst1.shape)
print("Size of Numpy Array:", lst1.size)
print("Number of Dimensions of Numpy Array:", lst1.ndim)
print("Item Size of Numpy Array (in bytes):", lst1.itemsize)
print(lst1.reshape(2,3))

Original List: [10, 20, 30, 40, 50, 60]
Numpy Array: [10 20 30 40 50 60]
Data Type of Numpy Array: int64
Shape of Numpy Array: (6,)
Size of Numpy Array: 6
Number of Dimensions of Numpy Array: 1
Item Size of Numpy Array (in bytes): 8
[[10 20 30]
 [40 50 60]]


In [2]:
lst1[0]

np.int64(10)

In [3]:
lst1[2]

np.int64(30)

In [4]:
lst1[-1]

np.int64(60)

In [5]:
lst1[2]

np.int64(30)

In [6]:
lst1[1:4]

array([20, 30, 40])

In [7]:
lst1[::2]

array([10, 30, 50])